### ISSUE TITLE
Missing smtp server configuration for staging/production 

### ISSUE THREAD

**Issue by colinux** [Evolix/chexpire#17]

**Comment by colinux** [comment]
Dynamic action mailler configuration has been added with 8ff94076c02fa49ac53cf91d66bfa4b21cca3659

On our server the delivery method needs to be configured in `config/chexpire.yml` file (the shared file):

```yaml
staging:
  action_mailer_config:
    delivery_method: :sendmail
```
